#include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # public_member_api_docs: false
    # constant_identifier_names: false
    # lines_longer_than_80_chars: false
    # always_use_package_imports: false
    # camel_case_extensions: false
    # directives_ordering: false
    # sort_constructors_first: false
    # avoid_equals_and_hash_code_on_mutable_classes: false
    # use_build_context_synchronously: false
    # cascade_invocations: false
    # prefer_asserts_with_message: false
    # avoid_redundant_argument_values: false
