name: dota2_invoker_game
description: DOTA 2 Invoker practice game.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #State Management
  provider: ^6.0.0

  #Icons
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2

  #Utils
  flutter_svg: ^1.1.6
  audioplayers: ^0.20.0
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.10
  store_redirect: ^2.0.1
  flutter_config: ^2.0.0

  #Local Storage
  shared_preferences: ^2.0.17

  #Firebase
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.6

  #Animation
  lottie: ^1.4.2
  splash: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  snappable_thanos: ^0.0.4

  #Widgets
  sleek_circular_slider: ^2.0.1
  flutter_arc_text: ^0.5.0

  #Ads
  google_mobile_ads: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #Lint
  very_good_analysis: ^3.1.0


flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/images/splash_images/
    - assets/images/qwe_gifs/
    - assets/images/misc/
    - assets/images/elements/
    - assets/images/spells/
    - assets/images/achievements/
    - assets/images/bosses/
    - assets/images/items/

    - assets/sounds/fail_sounds/
    - assets/sounds/gg_sounds/
    - assets/sounds/loading_sounds/
    - assets/sounds/spell_sounds/
    - assets/sounds/spell_sounds/cast_trigger_sounds/
    - assets/sounds/misc/
    - assets/sounds/ability_on_cooldown/
    - assets/sounds/not_enough_mana/
    - assets/sounds/shop_sounds/
    - assets/sounds/item_sounds/
    - assets/sounds/boss_sounds/warlock/
    - assets/sounds/boss_sounds/omniknight/
    - assets/sounds/boss_sounds/riki/
    - assets/sounds/boss_sounds/huskar/
    - assets/sounds/boss_sounds/templar/
    - assets/sounds/boss_sounds/anti_mage/

    - assets/lottie/
    - assets/svg/