name: dota2_invoker
description: DOTA 2 Invoker practice game.

publish_to: 'none'

version: 1.2.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #State Management
  provider: ^6.0.0

  #Icons
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2

  #Utils
  audioplayers: ^0.20.0

  #Firebase
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1

  #Animation
  lottie: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_images/
    - assets/images/qwe_gifs/
    - assets/images/other/
    - assets/images/elements/
    - assets/images/spells/

    - assets/sounds/fail_sounds/
    - assets/sounds/gg_sounds/
    - assets/sounds/loading_sounds/
    - assets/sounds/spell_sounds/